#pragma once

#include "Types/RE/FO4/BSLight.h"
#include "Types/RE/FO4/NiPointLight.h"
#include "Types/RE/FO4/NiSpotLight.h"
#include "Types/RE/FO4/BSGraphics.h"
#include "BSWaterShaderProperty.h"
#include "BGSTerrainBlock.h"
#include "BSSubIndexTriShape.h"
#include "BSDynamicTriShape.h"
#include "RE/B/BSMultiBoundAABB.h"
#include "RE/B/BSMultiBoundNode.h"
#include "BSSkin.h"
#include "BSLightingShaderMaterials.h"
#include "Types/RE/FO4/ShadowSceneNode.h"
#include "Types/RE/FO4/NiIntegersExtraData.h"
#include "Types/RE/FO4/TESObjectLIGH.h"
