include(FetchContent)

FetchContent_Declare(
    nvrhi
    SOURCE_DIR ${CMAKE_SOURCE_DIR}/extern/NVRHI
)

set(NVRHI_BUILD_SHARED OFF CACHE BOOL "" FORCE)
set(NVRHI_WITH_VALIDATION ON CACHE BOOL "" FORCE)
set(NVRHI_INSTALL ON CACHE BOOL "" FORCE)
set(NVRHI_INSTALL_EXPORTS OFF CACHE BOOL "" FORCE)

set(NVRHI_WITH_VULKAN OFF CACHE BOOL "" FORCE)
set(NVRHI_WITH_RTXMU ON CACHE BOOL "" FORCE)
set(NVRHI_WITH_AFTERMATH ON CACHE BOOL "" FORCE)
set(NVRHI_WITH_NVAPI OFF CACHE BOOL "" FORCE)

set(NVRHI_WITH_DX11 OFF CACHE BOOL "" FORCE)
set(NVRHI_WITH_DX12 ON CACHE BOOL "" FORCE)
set(NVRHI_D3D12_WITH_DXR12_OPACITY_MICROMAP ON CACHE BOOL "" FORCE)

set(RTXMU_WITH_VULKAN OFF CACHE BOOL "" FORCE)

set(DXHEADERS_INSTALL OFF CACHE BOOL "" FORCE)

FetchContent_MakeAvailable(nvrhi)

target_link_libraries(
	${PROJECT_NAME}
	PRIVATE
	nvrhi_d3d12
	nvrhi
)