include(FetchContent)

FetchContent_Declare(
    nvrhi
    SOURCE_DIR ${CMAKE_SOURCE_DIR}/extern/NVRHI
)

set(NVRHI_BUILD_SHARED OFF CACHE BOOL "" FORCE)
set(NVRHI_WITH_VALIDATION ON CACHE BOOL "" FORCE)
set(NVRHI_INSTALL OFF CACHE BOOL "" FORCE)
set(NVRHI_INSTALL_EXPORTS OFF CACHE BOOL "" FORCE)

set(NVRHI_WITH_VULKAN ON CACHE BOOL "" FORCE)

# RTXMU disables OMM
set(NVRHI_WITH_RTXMU OFF CACHE BOOL "" FORCE)

set(NVRHI_WITH_AFTERMATH OFF CACHE BOOL "" FORCE)
set(NVRHI_WITH_NVAPI OFF CACHE BOOL "" FORCE)

set(NVRHI_D3D12_WITH_DXR12_OPACITY_MICROMAP OFF CACHE BOOL "" FORCE)

set(NVRHI_WITH_DX12 ON CACHE BOOL "" FORCE)
set(NVRHI_WITH_DX11 OFF CACHE BOOL "" FORCE)

# Disable driver version so NVAPI is used
if (NVRHI_WITH_NVAPI)
	set(NVRHI_D3D12_WITH_DXR12_OPACITY_MICROMAP OFF CACHE BOOL "" FORCE)
endif()

set(RTXMU_WITH_VULKAN OFF CACHE BOOL "" FORCE)
set(AUTO_LOCATE_VULKAN OFF CACHE BOOL "" FORCE)

set(DXHEADERS_INSTALL OFF CACHE BOOL "" FORCE)

if (NVRHI_WITH_NVAPI)
	include(nvapi)
endif()

FetchContent_MakeAvailable(nvrhi)

if (NVRHI_WITH_AFTERMATH)
add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "${CMAKE_CURRENT_BINARY_DIR}/_deps/aftermath-src/lib/x64/GFSDK_Aftermath_Lib.x64.dll"
        $<TARGET_FILE_DIR:${PROJECT_NAME}>
)
endif()

target_compile_definitions(nvrhi_vk PRIVATE NVRHI_SHARED_LIBRARY_BUILD=1)

target_link_libraries(
	${PROJECT_NAME}
	PRIVATE
	nvrhi_d3d12
	nvrhi
	nvrhi_vk
	Vulkan::Headers
)